name: Kleinanzeigen Bot Runner

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutupsaneleri Yukle
        run: pip install -r requirements.txt

      - name: Botu Calistir
        env: 
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
        run: python bot.py
